- name: Deploy React App with Nginx and Firewall
  hosts: servers
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_become_password: "server"
  roles:
    - nginx
    - react_app
    - firewall
