name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ansible install
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/server_ssh.pem
          chmod 600 ~/.ssh/server_ssh.pem
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/server_ssh.pem

      - name: Ð”Add server key to known_hosts
        run: |
          ssh-keyscan -H <server_ip_addr> >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i "${{ secrets.SERVER_IP }}," deploy-react.yml --user=server
